project_id = "obbyvxodxvgdaarzmsbd"

[functions.webrtc-signaling]
verify_jwt = false

[functions.generate-consultation-summary]
verify_jwt = true

[functions.send-notification]
verify_jwt = true

[functions.analyze-reports]
verify_jwt = true

[functions.clinical-analysis]
verify_jwt = true